application:
  name: quarkus-vertx-example
  project: quarkus-vertx
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: my-postgresql-3498225
routers:
- name: main
  routes:
  - application_name: quarkus-vertx-example
    paths:
    - /*
